version: "3.7"
services:
  db:
    image: postgres:15.1
    restart: always
    container_name: ds_db
    environment:
      POSTGRES_DB: ds
      POSTGRES_USER: ds
      POSTGRES_PASSWORD: ds
    ports:
      - "5432:5432"
    volumes:
      - type: volume
        source: ds-db-volume
        target: /var/lib/postgresql/data
    networks:
      - ds_network

  app:
    build:
      context: .
    container_name: ds_app
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DB_DATABASE: ds
      DB_USERNAME: ds
      DB_PASSWORD: ds
      DB_HOST: db
      RAILS_ENV: production
      RAILS_SERVE_STATIC_FILES: "true"
      RAILS_LOG_TO_STDOUT: "true"
      DS_ENTRYPOINT: "true"
      CLASSIC_SMTP_ENABLED: "enabled"
      SMTP_HOST: "mailhog"
      SMTP_PORT: "1025"
      MAIL_FROM: "noreply.ds@interieur.gouv.fr"
      SMTP_USER: ""
      SMTP_PASS: ""
      SMTP_AUTHENTICATION: "plain"
    networks:
      - ds_network

  job:
    build:
      context: .
    container_name: ds_job
    depends_on:
      - db
    environment:
      DB_DATABASE: ds
      DB_USERNAME: ds
      DB_PASSWORD: ds
      DB_HOST: db
      RAILS_ENV: production
      RAILS_SERVE_STATIC_FILES: "true"
      RAILS_LOG_TO_STDOUT: "true"
      DS_ENTRYPOINT: "true"
      SMTP_HOST: "mailhog"
      SMTP_PORT: "1025"
      MAIL_FROM: "noreply.ds@interieur.gouv.fr"
      SMTP_USER: ""
      SMTP_PASS: ""
      SMTP_AUTHENTICATION: "plain"
    command: bundle exec rake jobs:work
    networks:
      - ds_network

  mailhog:
    container_name: ds_mailhog
    image: mailhog/mailhog
    restart: always
    ports:
      - 1025:1025
      - 8025:8025
    networks:
      - ds_network

networks:
  ds_network:
    name: ds_network
    driver: bridge

volumes:
  ds-db-volume:
